spring:
  application:
    name: produtos
  docker:
    compose:
      file: ./produtos/docker-compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5434/sgp?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      schema: ${spring.application.name}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  batch:
    jdbc:
      initialize-schema: always



server:
  port: 8082