spring:
  application:
    name: produtos
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name: ${spring.application.name}

  docker:
    compose:
      file: ./produtos/docker-compose.yaml
  datasource:
    url:
    driver-class-name:
    username:
    password:
    hikari:
      schema: ${spring.application.name}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8082